services:
  db:
    image: postgres:17
    container_name: apartment-manager-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: apartment_user
      POSTGRES_PASSWORD: apartment_password
      POSTGRES_DB: apartment_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: